# Generated by Django 6.0.5 on 2026-05-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new_field',
            field=models.CharField(blank=True, null=True),
        ),
    ]
