# Generated by Django 6.0.5 on 2026-05-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_moderated_at'),
        ('articles', '0002_article_new_field'),
    ]

    operations = [
    ]
