# Generated by Django 6.0.5 on 2026-05-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_merge_20260525_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='moderated_at',
        ),
        migrations.RemoveField(
            model_name='article',
            name='new_field',
        ),
        migrations.AlterModelTable(
            name='article',
            table='Статьи',
        ),
    ]
