# Generated by Django 6.0.5 on 2026-05-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_options_remove_article_moderated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В проверке'), ('moderated', 'Проверено')], default='new', max_length=25, verbose_name='Статус'),
        ),
    ]
