# Generated by Django 6.0.5 on 2026-05-27 13:47

from django.db import migrations


def set_required_statuses_to_articles(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    articles_to_moderate = Article.objects.filter(author__startswith="Автор")

    for article in articles_to_moderate:
        article.status = "moderated"
        article.save()


def rollback(apps, schema_editor):
    Article = apps.get_model('articles', 'Article')
    moderated_articles = Article.objects.filter(author__startswith="Автор")

    for article in moderated_articles:
        article.status = "new"
        article.save()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_status'),
    ]

    operations = [
        migrations.RunPython(set_required_statuses_to_articles, rollback),
    ]
