# Generated by Django 6.0.5 on 2026-06-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_set_required_statuses_to_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved', 'Одобрено'), ('Return_for_revision', 'Отправлено на доработку')], default='new', max_length=25, verbose_name='Статус'),
        ),
    ]
