# Generated by Django 6.0.5 on 2026-06-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_tags_alter_articletag_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
